export const data = {
  labels: ['country', 'hip hop', 'pop', 'rock', 'soul/r&b', 'reggae', 'electronic', 'punk', 'latin', 'polka', 'funk', 'jazz', 'metal'],
  datasets: [
    {
      label: 'no. of listens',
      backgroundColor: [
        'hsla(348, 85%, 54%, 1)',
        'hsla(49, 93%, 67%, 1)',
        'hsla(113, 52%, 83%, 1)',
        'hsla(213, 96%, 11%, 1)',
        'hsla(212, 17%, 33%, 1)',
        'hsla(245, 9%, 27%, 1)',
        'hsla(56, 6%, 51%, 1)',
        'hsla(175, 91%, 87%, 1)',
        'hsla(52, 96%, 69%, 1)',
        'hsla(4, 35%, 56%, 1)',
        'hsla(201, 21%, 48%, 1)',
        'hsla(31, 11%, 54%, 1)',
        'hsla(36, 61%, 64%, 1)',
        'hsla(31, 54%, 59%, 1)'
      ],
      borderColor: [
        'hsla(348, 85%, 54%, 1)',
        'hsla(49, 93%, 67%, 1)',
        'hsla(113, 52%, 83%, 1)',
        'hsla(213, 96%, 11%, 1)',
        'hsla(212, 17%, 33%, 1)',
        'hsla(245, 9%, 27%, 1)',
        'hsla(56, 6%, 51%, 1)',
        'hsla(175, 91%, 87%, 1)',
        'hsla(52, 96%, 69%, 1)',
        'hsla(4, 35%, 56%, 1)',
        'hsla(201, 21%, 48%, 1)',
        'hsla(31, 11%, 54%, 1)',
        'hsla(36, 61%, 64%, 1)',
        'hsla(31, 54%, 59%, 1)'
      ],
      borderWidth: 2,
      data: [
        [{ 'id': 1, 'song_name': 'Senger-Johnston', 'artist': 'regional', 'genre': 'Drama|Romance', 'year': '9/30/2022', 'subgenre': 'Moonlight and Valentino' },
          { 'id': 2, 'song_name': 'Schumm LLC', 'artist': 'uniform', 'genre': 'Action|Drama|War', 'year': '4/13/2022', 'subgenre': 'Heaven & Earth' },
          { 'id': 3, 'song_name': 'Ritchie, Schmidt and Hoppe', 'artist': 'Function-based', 'genre': 'Drama', 'year': '10/1/2022', 'subgenre': 'Separation, A (Jodaeiye Nader az Simin)' },
          { 'id': 4, 'song_name': 'Kulas, Hintz and Weimann', 'artist': 'Reverse-engineered', 'genre': 'Drama', 'year': '10/15/2022', 'subgenre': 'Dog Days (Hundstage)' },
          { 'id': 5, 'song_name': 'Rath-Kilback', 'artist': 'Enhanced', 'genre': 'Comedy', 'year': '6/13/2022', 'subgenre': 'All That... for This?!' },
          { 'id': 6, 'song_name': 'Jerde-Schinner', 'artist': 'intangible', 'genre': 'Animation', 'year': '1/7/2023', 'subgenre': 'Claymation Comedy of Horrors' },
          { 'id': 7, 'song_name': 'Osinski-Ferry', 'artist': 'Down-sized', 'genre': 'Documentary', 'year': '2/20/2022', 'subgenre': 'Punk Singer, The' },
          { 'id': 8, 'song_name': 'Johnson, Corwin and Abshire', 'artist': 'upward-trending', 'genre': 'Comedy|Drama|Western', 'year': '5/3/2022', 'subgenre': 'Big Hand for the Little Lady, A' },
          { 'id': 9, 'song_name': 'Buckridge-Gerlach', 'artist': 'hybrid', 'genre': 'Horror|Thriller', 'year': '5/10/2022', 'subgenre': 'Stepfather II' },
          { 'id': 10, 'song_name': 'Ebert-Maggio', 'artist': 'firmware', 'genre': 'Crime|Film-Noir', 'year': '12/1/2022', 'subgenre': 'Killing, The' },
          { 'id': 11, 'song_name': 'Harvey-Welch', 'artist': 'bottom-line', 'genre': 'Comedy', 'year': '11/17/2022', 'subgenre': 'Road to Utopia' },
          { 'id': 12, 'song_name': 'Sporer, Anderson and Davis', 'artist': 'Down-sized', 'genre': 'Drama|Horror', 'year': '4/3/2022', 'subgenre': 'Page of Madness, A (Kurutta ippêji)' },
          { 'id': 13, 'song_name': 'Klocko-Mertz', 'artist': 'projection', 'genre': 'Drama', 'year': '1/14/2023', 'subgenre': 'Sweet Dreams' },
          { 'id': 14, 'song_name': 'Steuber Group', 'artist': 'Digitized', 'genre': 'Western', 'year': '2/10/2022', 'subgenre': 'Arizona Raiders' },
          { 'id': 15, 'song_name': 'Keeling, Gutmann and Kunde', 'artist': 'actuating', 'genre': 'Drama|Romance|Thriller', 'year': '8/26/2022', 'subgenre': 'Before the Rains' },
          { 'id': 16, 'song_name': 'Klocko-Senger', 'artist': 'Reduced', 'genre': 'Action|Crime|Thriller', 'year': '5/22/2022', 'subgenre': 'Zero Tolerance (Noll tolerans)' },
          { 'id': 17, 'song_name': 'Goyette Inc', 'artist': 'Team-oriented', 'genre': 'Drama|Mystery', 'year': '6/7/2022', 'subgenre': 'Keyhole' },
          { 'id': 18, 'song_name': 'Cormier-Hermann', 'artist': 'flexibility', 'genre': 'Comedy', 'year': '3/1/2022', 'subgenre': 'Wishful Thinking' },
          { 'id': 19, 'song_name': 'Schiller, Padberg and Pollich', 'artist': 'responsive', 'genre': 'Drama', 'year': '12/29/2022', 'subgenre': 'Moment of Truth, The (Il momento della verità)' },
          { 'id': 20, 'song_name': 'Cremin Inc', 'artist': 'Mandatory', 'genre': 'Action|Thriller', 'year': '11/23/2022', 'subgenre': 'Driven' },
          { 'id': 21, 'song_name': 'Rippin Group', 'artist': 'Re-engineered', 'genre': 'Comedy|Musical|Romance', 'year': '12/5/2022', 'subgenre': 'Can-Can' },
          { 'id': 22, 'song_name': 'Kohler-Durgan', 'artist': 'heuristic', 'genre': 'Comedy|Drama|Romance', 'year': '7/7/2022', 'subgenre': "My Night At Maud's (Ma Nuit Chez Maud)" },
          { 'id': 23, 'song_name': 'Wiza, Jakubowski and Gorczany', 'artist': 'Object-based', 'genre': 'Crime|Drama|Thriller', 'year': '7/4/2022', 'subgenre': 'Taxi Driver' },
          { 'id': 24, 'song_name': 'McLaughlin Inc', 'artist': 'systematic', 'genre': 'Comedy|Drama|Romance', 'year': '2/28/2022', 'subgenre': 'Mozart and the Whale' },
          { 'id': 25, 'song_name': 'Ondricka and Sons', 'artist': 'matrices', 'genre': 'Drama', 'year': '1/16/2023', 'subgenre': 'Son of Babylon (Syn Babilonu)' },
          { 'id': 26, 'song_name': 'Batz, Langosh and Hayes', 'artist': 'tertiary', 'genre': 'Drama', 'year': '2/9/2022', 'subgenre': 'Two Queens and One Consort (Twee vorstinnen en een vorst)' },
          { 'id': 27, 'song_name': 'McDermott, Cormier and Rosenbaum', 'artist': 'flexibility', 'genre': 'Drama|Sci-Fi|Thriller', 'year': '8/23/2022', 'subgenre': 'Virtuality' },
          { 'id': 28, 'song_name': 'Strosin and Sons', 'artist': 'empowering', 'genre': 'Drama|Mystery', 'year': '9/8/2022', 'subgenre': 'Birth' },
          { 'id': 29, 'song_name': 'Swaniawski-Kessler', 'artist': 'adapter', 'genre': 'Comedy|Drama|Romance', 'year': '1/31/2023', 'subgenre': 'Scenes of a Sexual Nature' },
          { 'id': 30, 'song_name': 'Jacobson, Miller and McDermott', 'artist': 'migration', 'genre': 'Drama|Romance', 'year': '7/19/2022', 'subgenre': 'Eat Pray Love' },
          { 'id': 31, 'song_name': 'Hermann, Wolff and Keeling', 'artist': 'Reduced', 'genre': 'Documentary', 'year': '8/7/2022', 'subgenre': 'Mutantes' },
          { 'id': 32, 'song_name': 'Cole LLC', 'artist': 'systemic', 'genre': 'Action|Crime|Drama', 'year': '3/11/2022', 'subgenre': 'Northwest' },
          { 'id': 33, 'song_name': 'Schneider-Dach', 'artist': 'standardization', 'genre': 'Drama', 'year': '6/8/2022', 'subgenre': 'Pohjanmaa' },
          { 'id': 34, 'song_name': 'Simonis-Hermiston', 'artist': 'contextually-based', 'genre': 'Documentary', 'year': '2/9/2022', 'subgenre': 'Charlie: The Life and Art of Charles Chaplin' },
          { 'id': 35, 'song_name': 'Rohan-McLaughlin', 'artist': 'Assimilated', 'genre': 'Crime|Thriller', 'year': '7/12/2022', 'subgenre': 'Horseman, The' },
          { 'id': 36, 'song_name': 'Sawayn and Sons', 'artist': 'De-engineered', 'genre': 'Comedy', 'year': '1/5/2023', 'subgenre': 'Jim Jefferies: I Swear to God' },
          { 'id': 37, 'song_name': 'Schaefer LLC', 'artist': 'paradigm', 'genre': 'Animation|Children|Fantasy|Romance', 'year': '10/15/2022', 'subgenre': 'Cinderella' },
          { 'id': 38, 'song_name': 'Langosh-Bins', 'artist': 'Graphic Interface', 'genre': 'Drama|Horror', 'year': '10/15/2022', 'subgenre': 'Twentynine Palms' },
          { 'id': 39, 'song_name': 'MacGyver, Hilpert and Cummings', 'artist': 'Multi-lateral', 'genre': 'Action|Adventure|Fantasy|Horror|Romance', 'year': '1/2/2023', 'subgenre': 'Chinese Ghost Story II, A (Sien nui yau wan II yan gaan do)' },
          { 'id': 40, 'song_name': 'Tromp, Franecki and Ortiz', 'artist': 'Cloned', 'genre': 'Horror', 'year': '11/10/2022', 'subgenre': 'Cool Air' },
          { 'id': 41, 'song_name': 'Vandervort, Wolf and Vandervort', 'artist': 'conglomeration', 'genre': 'Action|Drama|War', 'year': '9/9/2022', 'subgenre': 'Windtalkers' },
          { 'id': 42, 'song_name': 'Collins, Jaskolski and Kshlerin', 'artist': 'attitude-oriented', 'genre': 'Drama|Horror|Thriller', 'year': '10/26/2022', 'subgenre': 'Vinyan' },
          { 'id': 43, 'song_name': 'Stehr-Konopelski', 'artist': 'Public-key', 'genre': 'Action|Drama|Thriller', 'year': '4/20/2022', 'subgenre': 'Kingdom, The' },
          { 'id': 44, 'song_name': 'Roberts Group', 'artist': 'stable', 'genre': 'Drama', 'year': '2/4/2022', 'subgenre': 'Mother, I Love You' },
          { 'id': 45, 'song_name': 'Price, Runte and Mosciski', 'artist': 'hierarchy', 'genre': 'Documentary', 'year': '12/25/2022', 'subgenre': 'Huey P. Newton Story, A' },
          { 'id': 46, 'song_name': 'Ratke-Becker', 'artist': 'Integrated', 'genre': 'Comedy|Drama|Romance', 'year': '4/18/2022', 'subgenre': 'Just Buried' },
          { 'id': 47, 'song_name': 'Daugherty, Feest and Padberg', 'artist': 'Extended', 'genre': 'Comedy', 'year': '8/14/2022', 'subgenre': 'House Party 3' },
          { 'id': 48, 'song_name': 'Block Group', 'artist': 'implementation', 'genre': 'Drama', 'year': '1/28/2023', 'subgenre': 'Carnegie Hall' },
          { 'id': 49, 'song_name': 'Lesch-Okuneva', 'artist': 'static', 'genre': 'Comedy|Crime|Drama', 'year': '10/21/2022', 'subgenre': 'Delhi-6' },
          { 'id': 50, 'song_name': 'Will LLC', 'artist': 'Cloned', 'genre': 'Action|Crime|Drama', 'year': '1/12/2023', 'subgenre': 'State Property' }]
      ]

    }
  ]

};
